mail.smtp.host=smtp.gmail.com
mail.smtp.port=587
mail.smtp.username=cpportal.auth@gmail.com
mail.smtp.password=abdluwczmsyltoqa
mail.smtp.auth=true
mail.smtp.starttls.enable=true
mail.from=cpportal.auth@gmail.com